# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_id', models.CharField(max_length=100, unique=True)),
                ('practice_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ['practice_name'],
            },
        ),
        migrations.CreateModel(
            name='facebookuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ok_to_text', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True)),
                ('consultation_date', models.DateField(blank=True, null=True)),
                ('consultation_time', models.TimeField(blank=True, null=True)),
                ('facebook_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LasikBot.facebookuser')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LasikBot.client')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LasikBot.client'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([('facebook_user', 'practice')]),
        ),
    ]
